Sis_RosangelaCunha/Models/ItemAnexado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sis_RosangelaCunha.Models
{
    public class ItemAnexado
    {
        public int ItensId { get; set; }

        public string Nome { get; set; }
        
        public string MimeType { get; set; }
        
        public AquisicaoContrato objAquisicao { get; set; }
        
        public virtual byte[] Arquivo { get; set; }

        //public virtual string Nome { get; set; }

        //public virtual string Local { get; set; }

        //public virtual string MimeType { get; set; }

        //public virtual string RowGuid { get; set; }



        public ItemAnexado()
        {
            objAquisicao = new AquisicaoContrato();
        }
    }
}

Sis_RosangelaCunha/Controllers/ItemAnexadoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sis_RosangelaCunha.Autenticacao;
using Sis_RosangelaCunha.DAO;
using Sis_RosangelaCunha.Models;
using System.IO;

namespace Sis_RosangelaCunha.Controllers
{
     //[Autorizar]
    public class ItemAnexadoController : Controller
    {
        private readonly ItemAnexadoDAO itemDAO = new ItemAnexadoDAO();
        private readonly AquisicaoContratoDAO aquisicaoDAO = new AquisicaoContratoDAO();

        #region Novo
        public ActionResult Novo(int aquisicaoId)
        {
            return View(aquisicaoId);
        }
        [HttpPost]
        public ActionResult Novo(ItemAnexado item, int aquisicaoId)
        {
            if (ModelState.IsValid)
            {
                item.objAquisicao.AquisicaoId = aquisicaoId;
                itemDAO.Inserir(item);
                return RedirectToAction("Listar");
            }
            return View(item);
        }
        #endregion
        #region Listar
        public ActionResult Listar()
        {
            IList<ItemAnexado> item = itemDAO.BuscarTodos();
            return View(item);
        }
        #endregion
        #region Editar
        public ActionResult Editar(int id)
        {
            ItemAnexado item = itemDAO.Buscar(id);
            ViewBag.aquisicaoId = new SelectList(aquisicaoDAO.BuscarTodos(), "aquisicaoId", "dataAquisicao");
            return View(item);
        }
        [HttpPost]
        public ActionResult Editar(ItemAnexado item, int aquisicaoId)
        {
            if (ModelState.IsValid)
            {
                item.objAquisicao.AquisicaoId = aquisicaoId;
                itemDAO.Alterar(item);
                return RedirectToAction("Listar");
            }
            ViewBag.aquisicaoId = new SelectList(aquisicaoDAO.BuscarTodos(), "aquisicaoId", "dataAquisicao");
            return View(item);
        }
        #endregion
        #region Excluir
        public ActionResult Excluir(int id)
        {
            ItemAnexado item = itemDAO.Buscar(id);
            return View(item);
        }
        [HttpPost]
        public ActionResult Excluir(ItemAnexado objItem)
        {
            itemDAO.Excluir(objItem);
            return RedirectToAction("Listar");
        }
        #endregion

        public ActionResult Upload()
        {
            int arquivosSalvos = 0;
            for (int i = 0;i <Request.Files.Count; i++)
            {
                HttpPostedFileBase arquivo = Request.Files[i];
                //Valivadções...
                if(arquivo.ContentLength > 0)
                {
                    var upload = Server.MapPath("~/Content/Uploads");
                    string caminhoArquivo = Path.Combine(@upload, Path.GetFileName(arquivo.FileName));
                    arquivo.SaveAs(caminhoArquivo);
                    arquivosSalvos++;
                }

            }
            ViewData["Message"] = String.Format("{0} Arquivos(s) salvo(s) com sucesso.", arquivosSalvos);
            return View("Upload");
        }


        [HttpPost]
        public ActionResult SaveFiles(string Id)
        {
            var context = this.HttpContext.ApplicationInstance.Context;

            context.Response.ContentType = "text/plain";

            bool isSavedSuccessfully = true;

            string fName = "";

            foreach (string fileName in HttpContext.Request.Files)
            {
                var file = Request.Files[fileName];
                fName = file.FileName;

                if (file != null && file.ContentLength > 0)
                {
                    var basedir = ConfigurationManager.AppSettings["basedir"].ToString();
                    var originalDirectory = new DirectoryInfo(string.Format("{0}{1}", Server.MapPath(@"\Content\"), basedir));


                    string pathString = Path.Combine(originalDirectory.ToString(), "imagepath");
                    var fileName1 = Path.GetFileName(file.FileName);
                    bool isExists = Directory.Exists(pathString);

                    if (!isExists)
                        Directory.CreateDirectory(pathString);

                    var path = string.Format("{0}\\{1}", pathString, file.FileName);

                    try
                    {
                        file.SaveAs(path);

                        var _repo = new ItemAnexadoDAO();
                        _repo.InserirArquivoEmpresa(path, Convert.ToInt32(Id), file.ContentType);
                        
                        System.IO.File.Delete(path);
                    }
                    catch (Exception ex)
                    {
                        var message = string.Format("Erro ao salvar arquivo | Mensagem : {0}", ex.Message);

                        //InserirLog("ARQUIVO EMPRESA", message);

                        isSavedSuccessfully = false;
                    }
                }
            }

            if (isSavedSuccessfully)
            {
                //InserirLog("ARQUIVO EMPRESA", "Arquivo gravado", "Sucesso");
                return Json(new { Message = fName });
            }
            else
            {
                //InserirLog("ARQUIVO EMPRESA", "Erro ao salvar arquivo");
                return Json(new { Message = "Erro ao salvar arquivo" });
            }
        }


        /// <summary>
        /// Get Upload File
        /// </summary>
        /// <param name="idArquivo">id do Arquivo</param>
        /// <returns></returns>
        public FileContentResult GetUploadedFile(int idArquivo)
        {
            var arquivo = new ItemAnexado();

            var _repo = new ItemAnexadoDAO();
                arquivo = _repo.Buscar(idArquivo);
            
            return File(arquivo.Arquivo, arquivo.MimeType, arquivo.Nome);
        }
    }
}

Sis_RosangelaCunha/Views/ItemAnexado/Editar.cshtml
@model Sis_RosangelaCunha.Models.ItemAnexado
@{
    ViewBag.Title = "Editar";
}
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h2>Novo Usúario</h2>
        <hr />
        <div class="=form-group">
            @Html.LabelFor(model => model.NomeArquivo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NomeArquivo, new { @class = "form-control" })
            </div>
        </div>
        <input type="submit" value="Salvar" class="btn btn-sm btn-success">
    </div>
}

Sis_RosangelaCunha/Views/ItemAnexado/Excluir.cshtml
@model Sis_RosangelaCunha.Models.ItemAnexado
@{
    ViewBag.Title = "Excluir";
}
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h2>Novo Item</h2>
        <hr />
        <div class="=form-group">
            @Html.LabelFor(model => model.NomeArquivo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.NomeArquivo, new { @class = "form-control" })
            </div>
        </div>
        <input type="submit" value="Excluir" class="btn btn-sm btn-success">
    </div>
}

Sis_RosangelaCunha/Views/ItemAnexado/Listar.cshtml
@model IEnumerable<Sis_RosangelaCunha.Models.ItemAnexado>
<!-- Page Content -->
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">

                <a class="thumbnail" href="#">
                    @if (item.Nome.Contains("png") || item.Nome.Contains("jpg") || item.Nome.Contains("jpeg"))
                    {
                        <img src="/ItemAnexado/GetUploadedFile/?idArquivo=@item.ItensId" alt="@item.Nome" title="@item.Nome" />
                    }
                    else
                    {
                        <img src="~/Content/images/default.jpg" />
                    }
                </a>
                @item.Nome
                <a href="/ItemAnexado/GetUploadedFile/?idArquivo=@item.ItensId" alt="Baixar Arquivo" title="Baixar Arquivo">
                    <i class="fa fa-download"></i>
                </a>
                |
                <a href="javascript:void(0);" onclick="ExcluirArquivo(@item.ItensId);" alt="Excluir Arquivo" title="Excluir Arquivo">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        }
    </div>
</div>

Sis_RosangelaCunha/Views/ItemAnexado/Novo.cshtml
@model Int16
@{
    ViewBag.Title = "Novo";
}

@section style{
    
    <link href="@Url.Content("~/Content/jquey-ui/jquery-ui.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Scripts/dropzone/basic.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Scripts/dropzone/dropzone.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/dropzone-main.css")" rel="stylesheet" />
    
    <style>
        .row {
            margin-top: 10px !important;
        }

        .thumb {
            margin: 10px;
            background-color: #FFF;
            padding: 10px;
        }
    </style>
}

@section scripts{
    <script src="@Url.Content("~/Scripts/jquery-ui.min.js")"></script>
    <script src="@Url.Content("~/Scripts/dropzone/dropzone.js")"></script>
    <script src="@Url.Content("~/Scripts/dropzone/dropzone-amd-module.min.js")"></script>
    <script src="@Url.Content("~/Scripts/basic-dropzone.js")"></script>
    <script src="~/Scripts/Sicov/itemanexdo.js"></script>
}



<form id="frmEmpresa" method="post" enctype="multipart/form-data">
    
    @Html.Hidden("Id", Model)

    <div class="form-group">
        <div id="actions" class="row">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="fa fa-plus"></i>
                    Adicionar Arquivos...
                </span>
            </div>
            <div class="col-lg-5">
                <span class="fileupload-process">
                </span>
            </div>
        </div>
        <div class="table table-striped" class="files" id="previews">
            <div id="template" class="file-row">
                <!-- This is used as the file preview template -->
                <div>
                    <span class="preview"><img data-dz-thumbnail /></span>
                </div>
                <div>
                    <p class="name" data-dz-name></p>
                    <strong class="error text-danger" data-dz-errormessage></strong>
                </div>
                <div>
                    <p class="size" data-dz-size></p>
                    @*<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                            <div class="progress-bar progress-bar-success" style="width:0%;" data-dz-uploadprogress></div>
                        </div>*@
                </div>
                <div>
                    <button class="btn btn-primary start fade">
                        <i class="fa fa-upload"></i>
                        <span>Upload</span>
                    </button>

                    <button data-dz-remove class="btn btn-warning cancel fade">
                        <i class="fa fa-times"></i>
                        <span>Cancelar</span>
                    </button>
                    <button data-dz-remove class="btn btn-danger delete">
                        <i class="fa-trash"></i>
                        <span>Excluir</span>
                    </button>
                </div>
            </div>
        </div>


        <!--ARQUIVOS-->
        <div id="listaArquivos" class="col-xs-12">
        </div>
        
        
        <a href="javascript:void(0);" class="btn btn-info" onclick="Upload();">Upload</a>

    </div>
</form>

Sis_RosangelaCunha/Views/ItemAnexado/Upload.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Upload</title>
    <link href="~/Content/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/multifile/jQuery.MultiFile.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#file').MultiFile({
                accept: 'pdf|jpg|pgn',
                max: 3,
                STRING: {
                    remove: 'Remover',
                    denied: 'Tipo do arquivo inválido $ext!',
                    duplicate: 'Esse arquivo já foi selecionado:\n$file!'
                }
            });
        });
    </script>
</head>
<body>
    <div class="container">
        <h2>Upload</h2>
        <h3>@Html.Encode(ViewData["Message"])</h3>
        @Html.BeginForm("Upload", "ItemAnexado", FormMethod.Post, new { enctype = "multipart/form-data" })

        <fieldset>
            <label for="nomeArquivo">Insira o Contrato Assinado: </label>
            <div>
                <input type="text" name="nomeArquivo">
                <input id="file" type="submit" value="Procurar..." />
            </div>
            <input type="submit" value="Enviar"/>
        </fieldset>
    </div>
</body>
</html>